import type { Metadata } from "next";
import { Inter, Manrope } from 'next/font/google';
import "./globals.css";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ['latin'] });
const manrope = Manrope({
  subsets: ['latin'],
  weight: ['800'], // ExtraBold = closest to Clash Display
  variable: '--font-heading',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${manrope.variable}`}>
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Barlow+Condensed:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
          rel="stylesheet"
        />
      </head>
      <body >
        {children}
        <Footer />
      </body>
    </html>
  );
}