import type { Metadata } from "next";
import { Inter, Manrope } from 'next/font/google';
import "./globals.css";

const inter = Inter({ subsets: ['latin'] });
const manrope = Manrope({
  subsets: ['latin'],
  weight: ['800'], // ExtraBold = closest to Clash Display
  variable: '--font-heading',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${manrope.variable}`}>
      <body className={inter.className}>
        {children}
      </body>
    </html>
  );
}